# Generated by scripts/render_formula.py; do not edit checksums manually.
cask "crew" do
  arch arm: "arm64", intel: "amd64"

  version "0.1.1"
  sha256 arm:   "66970ace76f75e113e51c0b2a5cc7aad0c61712f5b5f788b6af45f882ad1cce9",
         intel: "926cf0ad9988d4accbad827602d508fb1d9998f7e096106cd05fb23f31b427c8"

  url "https://github.com/tesserix/tesserix-crew/releases/download/v#{version}/crew_#{version}_darwin_#{arch}.tar.gz"
  name "Tesserix Crew"
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"

  binary "crew"
end
