# Generated by scripts/render_formula.py; do not edit checksums manually.
cask "crew" do
  arch arm: "arm64", intel: "amd64"

  version "0.1.0"
  sha256 arm:   "0fa325b31a354366fbaba00c8cdc033a54951fb10b6339405f6717a92c816146",
         intel: "817fa89513c2e1fd4a83d72ca18dfd1843c7ca392f9bb9ce66eb179627ec0715"

  url "https://github.com/tesserix/tesserix-crew/releases/download/v#{version}/crew_#{version}_darwin_#{arch}.tar.gz"
  name "Tesserix Crew"
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"

  binary "crew"
end
