# Generated by scripts/render_formula.py; do not edit checksums manually.
cask "crew" do
  arch arm: "arm64", intel: "amd64"

  version "0.3.0"
  sha256 arm:   "e2b1a78c0182f2b5268e347c4994aabfaf4e13eea7172e9af10f76e83b2ed39c",
         intel: "3e0f619b4c47c45711d5a84e7effae723fe054e9ce9a106b46354cee826cedf8"

  url "https://github.com/tesserix/tesserix-crew/releases/download/v#{version}/crew_#{version}_darwin_#{arch}.tar.gz"
  name "Tesserix Crew"
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"

  binary "crew"
end
