# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudnav < Formula
  desc "Fast, keyboard-driven multi-cloud TUI for Azure, GCP, and AWS."
  homepage "https://github.com/tesserix/cloudnav"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.18.0/cloudnav_0.18.0_macos_x86_64.tar.gz"
      sha256 "349f1276fdde78e1d39120a1973ee7a9fbd41761af0990d3d9da1a4ee9d3d5c4"

      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.18.0/cloudnav_0.18.0_macos_arm64.tar.gz"
      sha256 "edfbc8ccbfb650e829c8ad4aa069d1c0d9bf3dc51693a39660c2640adede9208"

      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.18.0/cloudnav_0.18.0_linux_x86_64.tar.gz"
      sha256 "d900a2187aef40b65c24b6f370ad2cc8fa5fa2c89449f7f3a3ca98d37141287f"
      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.18.0/cloudnav_0.18.0_linux_arm64.tar.gz"
      sha256 "804a882bfcaf50de33edfc4bd6bcf8979bb3824ef89350d0b0a0c9db0a3d209e"
      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
  end

  test do
    system "#{bin}/cloudnav", "version"
  end
end
