# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudnav < Formula
  desc "Fast, keyboard-driven multi-cloud TUI for Azure, GCP, and AWS."
  homepage "https://github.com/tesserix/cloudnav"
  version "0.6.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.6.3/cloudnav_0.6.3_macos_x86_64.tar.gz"
      sha256 "41f66f6a36b17600ed57e24d9f574dfb20736268d48db9a0ce2fa844010d49fa"

      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.6.3/cloudnav_0.6.3_macos_arm64.tar.gz"
      sha256 "f4ae30d09f3898773dbb8900d5d9406aaa080ac53fa5bbf78ba546b8cef98846"

      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.6.3/cloudnav_0.6.3_linux_x86_64.tar.gz"
      sha256 "88c3f2b6b7306864a63c76e7644e40a3eea257094b449ca36cca0957194a2fab"
      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/cloudnav/releases/download/v0.6.3/cloudnav_0.6.3_linux_arm64.tar.gz"
      sha256 "993675288fcb116a29a05d0a7138b2939c55460c6faaf57949e55a1e18a674f9"
      define_method(:install) do
        bin.install "cloudnav"
        generate_completions_from_executable(bin/"cloudnav", "completion")
      end
    end
  end

  test do
    system "#{bin}/cloudnav", "version"
  end
end
