# Generated by scripts/render_formula.py; do not edit checksums manually.
class Crew < Formula
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.0/crew_0.3.0_darwin_arm64.tar.gz"
      sha256 "e2b1a78c0182f2b5268e347c4994aabfaf4e13eea7172e9af10f76e83b2ed39c"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.0/crew_0.3.0_darwin_amd64.tar.gz"
      sha256 "3e0f619b4c47c45711d5a84e7effae723fe054e9ce9a106b46354cee826cedf8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.0/crew_0.3.0_linux_arm64.tar.gz"
      sha256 "d0f1bb93a817a9896f002358d1f622c2c2f9e65a4d0fc3950b543521a3b349d5"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.0/crew_0.3.0_linux_amd64.tar.gz"
      sha256 "c6cec99ef54826754a695b6ad5ef19dd373f7e7887ab42a1a6aa92823967bb37"
    end
  end

  def install
    bin.install "crew"
    pkgshare.install "THIRD_PARTY_LICENSES.txt"
  end

  test do
    assert_equal "crew #{version}\n", shell_output("#{bin}/crew version")
  end
end
