# Generated by scripts/render_formula.py; do not edit checksums manually.
class Crew < Formula
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.1/crew_0.3.1_darwin_arm64.tar.gz"
      sha256 "41371d5ef99c9e024bc8b24d5b9ca01ddf629da376ad27563873d6307664adf7"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.1/crew_0.3.1_darwin_amd64.tar.gz"
      sha256 "087b34749c0e0f260f1ef1496fa4139cf30ec9eb02acac4aa288ce31439122ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.1/crew_0.3.1_linux_arm64.tar.gz"
      sha256 "df931f7c7f0c94d28749f816a73e262618a26493e9f1f16110d0aca65fa70228"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.1/crew_0.3.1_linux_amd64.tar.gz"
      sha256 "e36d2d7dcbfa81df00af4409406c236deafd85117a9b3a0d41358ca149a0d195"
    end
  end

  def install
    bin.install "crew"
    pkgshare.install "THIRD_PARTY_LICENSES.txt"
  end

  test do
    assert_equal "crew #{version}\n", shell_output("#{bin}/crew version")
  end
end
