# Generated by scripts/render_formula.py; do not edit checksums manually.
class Crew < Formula
  desc "One persistent coding session across your subscribed coding agents"
  homepage "https://github.com/tesserix/tesserix-crew"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.2/crew_0.3.2_darwin_arm64.tar.gz"
      sha256 "d09325c9ec673097c1273358e288107e060bd5a4c45f50805a82a79df5139eb2"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.2/crew_0.3.2_darwin_amd64.tar.gz"
      sha256 "0d1c769603a5ee80f9af09281d9614ed09c7607dcfa521674adaec0ab71c4471"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.2/crew_0.3.2_linux_arm64.tar.gz"
      sha256 "35c7a2a11052e369cb9a84c9e17b9f19ff427d7ee1e47a97c1a468ae348b735e"
    end

    on_intel do
      url "https://github.com/tesserix/tesserix-crew/releases/download/v0.3.2/crew_0.3.2_linux_amd64.tar.gz"
      sha256 "b28562c947326a266e062312fe781999f02fe0276a9c610bcc4c20f4bcaabc1d"
    end
  end

  def install
    bin.install "crew"
    pkgshare.install "THIRD_PARTY_LICENSES.txt"
  end

  test do
    assert_equal "crew #{version}\n", shell_output("#{bin}/crew version")
  end
end
