# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandboxctl < Formula
  desc "One-command local Kubernetes sandbox for macOS (kind + Argo CD + Kargo + Istio)"
  homepage "https://github.com/tesserix/sandboxctl"
  version "1.5.0"
  license "MIT"

  depends_on "helm"
  depends_on "kind"
  depends_on "kubectl"
  depends_on "podman" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tesserix/sandboxctl/releases/download/v1.5.0/sandboxctl_1.5.0_macOS_amd64.tar.gz"
      sha256 "c2615a53ad336d1636b5ca48d161b49f7268838741c3e135a0cc5c034cf461ca"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tesserix/sandboxctl/releases/download/v1.5.0/sandboxctl_1.5.0_macOS_arm64.tar.gz"
      sha256 "e0c7b65c6c65bbb80e179422372143a2538f63ddee47f0e5fbdf6c2559238b5a"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v1.5.0/sandboxctl_1.5.0_linux_amd64.tar.gz"
      sha256 "9506def00d4202042be2007eb64a2dc554c7ac07f156c74cc3a9bc938d43d2c7"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v1.5.0/sandboxctl_1.5.0_linux_arm64.tar.gz"
      sha256 "3f5f69b84ea125a17c18557b0d4c11ef50bf9ed7391d5502594f78bfd11b3d2e"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  test do
    assert_match "sandboxctl", shell_output("#{bin}/sandboxctl --help")
    assert_match version.to_s, shell_output("#{bin}/sandboxctl version")
  end
end
