# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandboxctl < Formula
  desc "One-command local Kubernetes sandbox for macOS (kind + Argo CD + Kargo + Istio)"
  homepage "https://github.com/tesserix/sandboxctl"
  version "2.8.4"
  license "MIT"

  depends_on "helm"
  depends_on "kind"
  depends_on "kubectl"
  depends_on "podman" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.8.4/sandboxctl_2.8.4_macOS_amd64.tar.gz"
      sha256 "82573c8963960cd2defc58c0ce249054e039e3dab524b4e185e4a0900c174669"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.8.4/sandboxctl_2.8.4_macOS_arm64.tar.gz"
      sha256 "b821fd130b1b72be469a20c49233a97ea82f1763a66fe861401c25bba126a18e"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.8.4/sandboxctl_2.8.4_linux_amd64.tar.gz"
      sha256 "ba917bfc2ae2f35ed33c678095cde4dae3b46855e1e4edcd92dd2be93a40ca9e"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.8.4/sandboxctl_2.8.4_linux_arm64.tar.gz"
      sha256 "2957075998dfe88ae31e457b8d7794050d9ec960b8c53b1244c450842012044b"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  test do
    assert_match "sandboxctl", shell_output("#{bin}/sandboxctl --help")
    assert_match version.to_s, shell_output("#{bin}/sandboxctl version")
  end
end
