# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandboxctl < Formula
  desc "One-command local Kubernetes sandbox for macOS (kind + Argo CD + Kargo + Istio)"
  homepage "https://github.com/tesserix/sandboxctl"
  version "2.4.0"
  license "MIT"

  depends_on "helm"
  depends_on "kind"
  depends_on "kubectl"
  depends_on "podman" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.4.0/sandboxctl_2.4.0_macOS_amd64.tar.gz"
      sha256 "aca8cac669b5be9d9dd6b5ce175b38875c4581eb044b2760b955d3e6903648d8"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.4.0/sandboxctl_2.4.0_macOS_arm64.tar.gz"
      sha256 "6552ed7f6132edec6ac4afbcad3cd3d06325441923b95675d3a229e795c0530a"

      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.4.0/sandboxctl_2.4.0_linux_amd64.tar.gz"
      sha256 "dd36bbaccf8624acc8461551cfad2cf6525d052bb9cdf9d9d74bacb7fc77a6ab"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tesserix/sandboxctl/releases/download/v2.4.0/sandboxctl_2.4.0_linux_arm64.tar.gz"
      sha256 "3616e55be15ebbf1e8438eaabd07c1a929bd07a9997604b71d62014a56743cb0"
      define_method(:install) do
        libexec.install "sandboxctl" => "sandboxctl-bin"
        libexec.install "sandbox.sh", "kind-config.yaml", "manifests", "lib"
        (bin/"sandboxctl").write <<~EOS
          #!/bin/bash
          export SANDBOXCTL_ASSETS="#{libexec}"
          exec "#{libexec}/sandboxctl-bin" "$@"
        EOS
        (bin/"sandboxctl").chmod 0755
      end
    end
  end

  test do
    assert_match "sandboxctl", shell_output("#{bin}/sandboxctl --help")
    assert_match version.to_s, shell_output("#{bin}/sandboxctl version")
  end
end
